### ISSUE TITLE
Missing debian package for 2.6.1

### ISSUE THREAD

**Issue by ekeih** [Icinga/deb-icingaweb2#2]
Hi,

a week ago 2.6.1 was released but there is no package in http://packages.icinga.com/ubuntu/dists/icinga-xenial/main/binary-amd64/Packages

Best regards
Max

**Comment by dnsmichi** [comment]
Yep, that is blocked by this issue: https://github.com/Icinga/icinga-packaging/issues/111

The release announcement is therefore pending, and as such, nothing is officially released :)

**Comment by ekeih** [comment]
Thanks for the clarification!
This also explains why I was so surprised by https://github.com/Icinga/icingaweb2/releases/tag/v2.6.1. I thougt... "Wow I totally missed the release announcement"... well apparently I did not miss it ;)
